### ISSUE TITLE
Why not use IPFS?

### ISSUE THREAD

**Issue by milezzz** [ItalyPaleAle/hereditas#16]
Awesome project! But one thing...

If you die and don't pay your hosting bill the deadman switch is toast. Seems really logical to push the static site to IPFS, is this being considered?

EDIT: Oh just noticed this: https://github.com/ItalyPaleAle/hereditas/blob/f35dfe00b041b8a91d8c7d35eb5dbe2724448158/azure-pipelines.yaml

I guess this is being planned?

**Comment by ItalyPaleAle** [comment]
You can host your box (after building it) anywhere, including on IPFS! In fact, I have a copy of my own box on IPFS too :)

Two things to keep in mind:

1. You need some node pinning your files up on IPFS. You can use a service like Piñata, for example. I’d say don’t host your own, because of the issues with the server being shut down otherwise
2. On Auth0 you’ll need to whitelist all the possible URLs where your box will be. This means, you’ll have to whitelist `http://localhost:8080` for the local gateway, as well as every single gateway you’ll whitelist (And change the address when the IPFS hash changes)
